# Generated by Django 5.2.5 on 2025-09-17 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('text', 'Text')], default='image', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('credit_cost', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai/models/inputs/')),
                ('prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='ai/models/overlays/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credits_charged', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_runs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_runs', to='emr_app.patient')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ai_models_app.aimodeltool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
