# Generated by Django 5.2.5 on 2025-08-24 13:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Are you a woman?', max_length=1)),
                ('ethnicity', models.CharField(choices=[('1', 'White'), ('2', 'African American'), ('3', 'Other race or ethnicity')], help_text='Race and ethnicity', max_length=1)),
                ('alcohol', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you drink alcohol everyday?', max_length=1)),
                ('alcohol_amount', models.CharField(blank=True, choices=[('1', '1 drink'), ('2', '2 or more drinks')], help_text='How much alcoholic drink do you consume in a day?', max_length=1, null=True)),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height', models.DecimalField(decimal_places=1, help_text='Height in centimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('physical_activity', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Are you physically active?', max_length=1)),
                ('children_before_30', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had children before the age of 30?', max_length=1)),
                ('breastfeeding', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had breastfeeding that lasted for a year or more?', max_length=1)),
                ('birth_control', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had Birth Control Plan?', max_length=1)),
                ('hormone_therapy', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had post-menopausal hormone therapy?', max_length=1)),
                ('hormone_therapy_type', models.CharField(blank=True, choices=[('1', 'Combined HT (Estrogen + Progesterone)'), ('2', 'ERT (Estrogen Replacement Therapy)')], help_text='Type of hormone therapy', max_length=1, null=True)),
                ('menstrual_start', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Did your menstrual periods start before age 12?', max_length=1)),
                ('menopause_age', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Did you go through menopause after age 55?', max_length=1)),
                ('breast_implants', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you have breast implants?', max_length=1)),
                ('radiation_therapy', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you been treated with radiation therapy to the chest for another cancer?', max_length=1)),
                ('dense_breast', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Has dense breast tissue been reported in your mammogram?', max_length=1)),
                ('des_exposure', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had exposure to diethylstilbestrol (DES)?', max_length=1)),
                ('breast_biopsy', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you ever had a breast biopsy for a reason other than cancer?', max_length=1)),
                ('biopsy_report', models.CharField(blank=True, choices=[('1', 'Fibrosis'), ('2', 'Simple cysts (fibrocystic changes)'), ('3', 'Mild hyperplasia'), ('4', 'Adenosis'), ('5', 'Phyllodes tumor'), ('6', 'A single papilloma'), ('7', 'Fat necrosis'), ('8', 'Duct ectasia'), ('9', 'Periductal fibrosis'), ('10', 'Squamous and apocrine metaplasia'), ('11', 'Epithelial-related calcifications'), ('12', 'Lipoma'), ('13', 'Hamartoma'), ('14', 'Hemangioma'), ('15', 'Neurofibroma'), ('16', 'Adenomyoepithelioma'), ('17', 'Mastitis (infection of the breast)'), ('18', 'Usual ductal hyperplasia (without atypia)'), ('19', 'Fibroadenoma'), ('20', 'Sclerosing adenosis'), ('21', 'Several papillomas (papillomatosis)'), ('22', 'Radial scar'), ('23', 'Atypical ductal hyperplasia (ADH)'), ('24', 'Atypical lobular hyperplasia (ALH)'), ('25', 'Lobular carcinoma in situ (LCIS)')], help_text='Which of the following is mentioned in your biopsy report?', max_length=2, null=True)),
                ('family_history_female', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had family history of breast cancer in your mother, sister or daughter?', max_length=1)),
                ('family_history_count', models.PositiveIntegerField(blank=True, help_text='How many of your family (mother, sister, daughter) have had breast cancer?', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('family_history_male', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had family history of breast cancer in your father or brother?', max_length=1)),
                ('personal_history', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had personal history of breast cancer in one breast?', max_length=1)),
                ('tall', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Are you taller than 170 centimeters?', max_length=1)),
                ('genetic_test', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Have you had genetic test for breast cancer related gene mutations (BRCA1, BRCA2)?', max_length=1)),
                ('genetic_test_result', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], help_text='Is your test result positive for BRCA1 or BRCA2?', max_length=1, null=True)),
                ('diet', models.CharField(choices=[('1', 'High fat diets'), ('2', 'High in fruits and vegetables and calcium-rich dairy diets'), ('3', 'Low in red and processed meats'), ('4', 'Diets high in soy products'), ('5', 'None of mentioned above')], help_text='Which of the following do you use in your daily regimen?', max_length=1)),
                ('smoking', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you smoke 20 or more cigarettes per day?', max_length=1)),
                ('smoking_timing', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], help_text='Did you begin smoking before the first pregnancy?', max_length=1, null=True)),
                ('night_shift', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you have night shift work?', max_length=1)),
                ('chemicals_environment', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you think chemicals in the environment are risk factors for breast cancer?', max_length=1)),
                ('controversial_factors', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], help_text='Do you think antiperspirants, bras, or abortion are risk factors for breast cancer?', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breast Cancer Risk Assessment',
                'verbose_name_plural': 'Breast Cancer Risk Assessments',
                'db_table': 'breast_cancer_risk_assessment',
                'ordering': ['-created_at'],
            },
        ),
    ]
