# Generated by Django 5.2.5 on 2025-08-24 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(help_text='ورود با شماره تلفن (E.164).', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در قالب E.164 باشد (مثال: +989121234567).', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('email', models.EmailField(blank=True, help_text='اختیاری، برای اعلان\u200cها و بازیابی.', max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('patient', 'Patient / کاربر عادی'), ('clinician', 'Clinician / ارائه\u200cدهنده'), ('admin', 'Organization Admin / ادمین')], default='patient', max_length=20)),
                ('locale', models.CharField(default='fa', help_text='زبان/محلی\u200cسازی پیش\u200cفرض رابط.', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='منطقهٔ زمانی کاربر.', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('tos_accepted', models.BooleanField(default=False, help_text='پذیرش شرایط استفاده.')),
                ('tos_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('basic', 'Basic (deprecated)'), ('advanced', 'Advanced (deprecated)')], default='basic', help_text='(Deprecated) لطفاً از subscriptions در purchase_app استفاده کنید.', max_length=10)),
                ('remaining_questions', models.IntegerField(default=0, help_text='(Deprecated) به\u200cجای این از Wallet/UsageLog برای محدودیت استفاده بهره ببرید.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['phone_number'], name='login_app_c_phone_n_e57ce4_idx'), models.Index(fields=['email'], name='login_app_c_email_a35f6b_idx')],
            },
        ),
    ]
